name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/ssh_key_workflow_setup/
          git pull origin main
          composer install
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          chown -R www-data:www-data .
          chmod -R 755 storage bootstrap/cache